import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api';
const api = axios.create({ baseURL: API });
const auth = () => ({ headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } });

function Login({ onLogin }) {
  const [username,setUsername]=useState('admin'); const [password,setPassword]=useState('admin123'); const [error,setError]=useState('');
  const submit=async e=>{e.preventDefault();try{const {data}=await api.post('/auth/login',{username,password});localStorage.setItem('token',data.token);onLogin();}catch{setError('Invalid credentials');}};
  return <div className="login"><form onSubmit={submit}><span className="eyebrow">AWS INFRASTRUCTURE</span><h1>Cloud Resource Monitor</h1><p>Sign in to view cloud telemetry.</p><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button type="submit">Sign in</button>{error&&<div className="error">{error}</div>}<small>Demo: admin / admin123</small></form></div>;
}
export default function App(){
 const [logged,setLogged]=useState(!!localStorage.getItem('token')); const [instances,setInstances]=useState([]); const [selected,setSelected]=useState(''); const [metrics,setMetrics]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const load=async()=>{setLoading(true);try{const {data}=await api.get('/monitoring/instances',auth());setInstances(data);setSelected(s=>s||data[0]?.id||'');setError('');}catch{setError('Unable to load instances. Check backend/AWS settings.');}finally{setLoading(false);}};
 const loadCpu=async id=>{if(!id)return;try{const {data}=await api.get(`/monitoring/instances/${id}/cpu?hours=3`,auth());setMetrics(data);}catch{setMetrics(null);}};
 useEffect(()=>{if(logged)load();},[logged]); useEffect(()=>{if(logged)loadCpu(selected);},[logged,selected]);
 const chartData=useMemo(()=>metrics?metrics.values.map((v,i)=>({time:new Date(metrics.timestamps[i]).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),cpu:Number(v.toFixed(2))})):[],[metrics]);
 if(!logged)return <Login onLogin={()=>setLogged(true)}/>;
 const running=instances.filter(i=>i.state==='running').length; const logout=()=>{localStorage.removeItem('token');setLogged(false);};
 return <div className="app"><header><div><span className="eyebrow">AWS INFRASTRUCTURE</span><h1>Cloud Resource Monitor</h1><p>EC2 performance and CloudWatch telemetry</p></div><div><button onClick={load}>↻ Refresh</button> <button onClick={logout}>Logout</button></div></header>{error&&<div className="error">{error}</div>}<section className="stats"><div><span>Instances</span><strong>{instances.length}</strong></div><div><span>Running</span><strong>{running}</strong></div><div><span>Stopped / other</span><strong>{instances.length-running}</strong></div><div><span>Mode</span><strong>{metrics?.source||'AWS'}</strong></div></section><main><section className="panel"><div className="panel-head"><h2>EC2 Instances</h2><p>{loading?'Loading resources…':'Select an instance to inspect metrics.'}</p></div><div className="table-wrap"><table><thead><tr><th>Instance</th><th>Name</th><th>Type</th><th>Status</th><th>Private IP</th></tr></thead><tbody>{instances.map(i=><tr key={i.id} className={selected===i.id?'selected':''} onClick={()=>setSelected(i.id)}><td><b>{i.id}</b></td><td>{i.name||'—'}</td><td>{i.type}</td><td><span className={`badge ${i.state}`}>{i.state}</span></td><td>{i.privateIp||'—'}</td></tr>)}{!instances.length&&!loading&&<tr><td colSpan="5" className="empty">No instances returned.</td></tr>}</tbody></table></div></section><section className="panel chart-panel"><div className="panel-head"><h2>CPU Utilization</h2><p>{selected||'No instance selected'} · Last 3 hours</p></div><div className="chart">{chartData.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={chartData}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis unit="%"/><Tooltip/><Line type="monotone" dataKey="cpu" name="CPU" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer>:<div className="empty">No metric points available.</div>}</div></section></main></div>;
}
